// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://rfbndl6g5ve5vb2gdbhbhdtwhq.appsync-api.me-south-1.amazonaws.com/graphql',
          region: 'me-south-1',
          defaultAuthMode: 'apiKey',
          apiKey: ''
        }
    }
};

export default config;